jikkou {
  provider.kafka {
    default = true
    type = io.jikkou.kafka.KafkaExtensionProvider
    config = {
      client {
        bootstrap.servers        = ${?KAFKA_BOOTSTRAP_SERVERS}
        security.protocol        = "SSL"
        ssl.truststore.location  = ${?KAFKA_TRUSTSTORE_PATH}
        ssl.truststore.password  = ${?KAFKA_TRUSTSTORE_PASSWORD}
        ssl.keystore.location    = ${?KAFKA_KEYSTORE_PATH}
        ssl.keystore.password    = ${?KAFKA_KEYSTORE_PASSWORD}
        ssl.key.password         = ${?KAFKA_KEY_PASSWORD}
      }
    }
  }

  repositories = [
    {
      name = "guardrails"
      type = io.jikkou.core.repository.GitHubResourceRepository
      config = {
        repository = "fhussonnois/orchestrating-streams"
        branch = "main"
        paths = ["jikkou/policies"]
        token = ${?GITHUB_TOKEN}
      }
    }
  ]
}
