id: generate_orders_to_postgres
namespace: orchestrating.streams.producer
description: |
  Flow to generate and insert random order data into PostgreSQL. 
  This flow is to be used with postgres_sql_to_kafka.yml
tasks:
  # Step 1: Ensure the table exists
  - id: create_table_if_not_exists
    type: io.kestra.plugin.jdbc.postgresql.Query
    description: Create the orders table if it doesn't exist.
    url: jdbc:postgresql://postgres:5432/kestra
    username: kestra
    password: k3str4
    sql: |
      CREATE TABLE IF NOT EXISTS orders (
        id SERIAL PRIMARY KEY,
        customer_name TEXT,
        product TEXT,
        quantity INT,
        price NUMERIC,
        created_at TIMESTAMP DEFAULT NOW(),
        processed BOOLEAN DEFAULT FALSE
      );

  # Step 2: Generate random order data
  - id: generate_orders
    type: io.kestra.plugin.datagen.Generate
    description: Generate random order data using the Datagen plugin.
    generator:
      type: io.kestra.plugin.datagen.generators.JsonObjectGenerator
      value:
        customer_name: "#{name.fullName}"
        price: "#{commerce.price}"
        quantity: "#{numerify '#'}"
        product: "#{commerce.productName.product}"

  # Step 3: Print generate random order data
  - id: debug
    type: io.kestra.plugin.core.log.Log
    message: "{{outputs.generate_orders.value}}"

  # Step 4: Insert generated orders into the database
  - id: insert_orders
    type: io.kestra.plugin.jdbc.postgresql.Query
    description: Insert generated orders into PostgreSQL.
    url: jdbc:postgresql://postgres:5432/kestra
    username: kestra
    password: k3str4
    sql: |
      INSERT INTO orders ("customer_name", "product", "quantity", "price")
      VALUES (
        '{{ outputs.generate_orders.value.customer_name }}',
        '{{ outputs.generate_orders.value.product }}',
        {{ outputs.generate_orders.value.quantity }},
        {{ outputs.generate_orders.value.price }}
      )
triggers:
  - id: every_5_seconds
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "*/5 * * * * *"
    withSeconds: true
    disabled: true
