id: trigger_datagen_to_kafka
namespace: orchestrating.streams.producer
tasks:
  - id: produce
    type: io.kestra.plugin.kafka.Produce
    topic: "datagen_topic"
    keySerializer: STRING
    valueSerializer: JSON
    properties:
      bootstrap.servers: "kafka:29092"
    from:
      key: "{{ trigger.value.email }}"
      value: "{{ trigger.value }}"
      headers:
        source: "/kestra/namespace/{{flow.namespace}}/flow/{{flow.id}}"
triggers:
  - id: datagen
    disabled: true
    type: io.kestra.plugin.datagen.core.Trigger
    interval: PT5S
    batchSize: 1
    generator:
      type: io.kestra.plugin.datagen.generators.JsonObjectGenerator
      value:
        name: "#{name.fullName}"
        email: "#{internet.emailAddress}"
        age: 30
        address:
          city: "#{address.city}"
          zip: "#{address.zipCode}"
        skills: [ "#{job.keySkills}", "#{job.position}", "hardcoded" ]
        ts: "{{ now() }}"